[package]
name = "rlucene"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
derive_getters = { path = "libs/derive_getters" }
crc32fast = "1.4.2"
byteorder = "1.5.0"
thiserror = "2.0.12"
num-bigint = "0.4.6"
regex = "1.11.1"
once_cell = "1.21.1"
rand = "0.9.0"
fs2 = "0.4.3"
chrono = "0.4.40"
num-traits = "0.2.19"
flate2 = "1.1.0"
strum = "0.27.1"
strum_macros = "0.27.1"

[dev-dependencies]
bit-set = "0.8.0"
rand_xoshiro = "0.7.0"
tempfile = "3.19.1"
num-integer="0.1.46"

[profile.dev]
overflow-checks = false

[features]
default= ["test_only", "not_required_in_rust_lucene", "wait_other_impl","unused"]
test_only = []
not_required_in_rust_lucene = []
wait_other_impl = []
test_log_verbose = []
nightly = []
unused = []
[workspace]
members = [
    ".",
    "libs/derive_getters",
]
