[tasks.tidy]
description = "Code tidy"
dependencies = ["check-rust-version","clippy", "fix","format"]

[tasks.commit]
description = "Full Check Before Commit"
dependencies = ["check-rust-version","clippy", "fix","format","check-uncommitted","test-light"]

[tasks.ci]
description = "Run ci"
dependencies = ["check-rust-version","clippy","fix", "format", "check-uncommitted","test"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
#args = ["clippy", "--fix", "--", "-D", "warnings"]
args = ["clippy", "--fix"]

[tasks.fix]
command = "cargo"
#args = ["clippy", "--fix", "--", "-D", "warnings"]
args = ["fix", "--allow-dirty", "--allow-staged"]

[tasks.test]
command = "cargo"
args = ["test", "--verbose", "--features", "test_log_verbose,nightly"]

[tasks.test-light]
command = "cargo"
args = ["test"]

[tasks.check-uncommitted]
description = "Check for uncommitted changes using Rust script"
script_runner = "@rust"
script = [
    '''
    fn main() {
        let output = std::process::Command::new("git")
            .args(["status", "--porcelain"])
            .output()
            .expect("failed to execute git");
        let stdout = String::from_utf8_lossy(&output.stdout);
        if stdout.trim().is_empty() {
            println!("✅ ✅ ✅ Working directory clean. All changes committed.");
        } else {
            eprintln!("❌ ❌ ❌ Uncommitted changes detected after code Check. Please commit your work first.");
            eprintln!("{}", stdout);
            std::process::exit(1);
        }
    }
    '''
]

[tasks.check-rust-version]
description = "Ensure exact Rust version"
env = { REQUIRED_RUST_VERSION = "1.88.0" }
script_runner = "@rust"
script = [
    '''
    use std::env;
    fn main() {
        let required = env::var("REQUIRED_RUST_VERSION")
            .expect("REQUIRED_RUST_VERSION is not set");

        let output = std::process::Command::new("rustc")
            .arg("--version")
            .output()
            .expect("failed to execute rustc");

        let stdout = String::from_utf8_lossy(&output.stdout);
        if !stdout.contains(&required) {
            eprintln!(" ❌ ❌ ❌ Rust version mismatch: expected {}, got: {}", required, stdout);
            std::process::exit(1);
        } else {
            println!(" ✅ ✅ ✅ Rust version OK: {}", stdout.trim());
        }
    }
    '''
]