[tasks.check]
description = "Code format"
dependencies = ["check-rust-version","clippy", "fix","format"]

[tasks.ci]
description = "Run ci"
dependencies = ["check-rust-version","clippy","fix", "format", "check-dirty","test"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
#args = ["clippy", "--fix", "--", "-D", "warnings"]
args = ["clippy", "--fix"]

[tasks.fix]
command = "cargo"
#args = ["clippy", "--fix", "--", "-D", "warnings"]
args = ["fix", "--allow-dirty", "--allow-staged"]

[tasks.test]
command = "cargo"
args = ["test", "--verbose", "--features", "test_log_verbose,nightly", "--", "--ignored"]

[tasks.check-dirty]
description = "Check if code was modified after auto-fix, and show diff details"
script = [
    "if ! git diff --exit-code > /dev/null; then",
    "  echo '❌ Rust code was not properly formatted. Please run 'cargo make check' and commit the changes';",
    "  git diff --color;",
    "  exit 1;",
    "else",
    "  echo '✅ Code-dirty check Ok';",
    "fi"
]
[tasks.check-rust-version]
description = "Ensure exact Rust version"
script_runner = "@rust"
script = [
    '''
    fn main() {
        let version = std::process::Command::new("rustc")
            .arg("--version")
            .output()
            .expect("failed to execute rustc");

        let stdout = String::from_utf8_lossy(&version.stdout);
        if !stdout.contains("1.84.0") {
            eprintln!("❌ Rust version mismatch: expected 1.84.0, got: {}", stdout);
            std::process::exit(1);
        } else {
            println!("✅ Rust version OK: {}", stdout);
        }
    }
    '''
]
