# Maximum line width in characters; lines longer than this will be wrapped.
max_width = 100
# Use spaces instead of tabs for indentation.
hard_tabs = false
# Sort and reorder `use` statements alphabetically.
reorder_imports = true
# Add a trailing comma to the last arm of multi-line `match` expressions.
match_block_trailing_comma = true
# Specify the Rust edition for formatting
edition = "2024"
group_imports = "StdExternalCrate" # 按标准库/外部库/本地分组
wrap_comments = true       # 自动换行长注释
trailing_comma = "Vertical" # 多行结构尾部逗号对齐
newline_style= "Unix" # 换行符风格
merge_derives=true