/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
pub(crate) mod base_compound_format_test_case;
pub mod base_compressing_doc_values_format_test_case;
pub mod base_doc_values_format_test_case;
pub(crate) mod base_field_info_format_test_case;
pub(crate) mod base_index_file_format_test_case;
pub mod base_knn_vectors_format_test_case;
pub(crate) mod base_live_docs_format_test_case;
pub(crate) mod base_merge_policy_test_case;
pub mod base_norms_format_test_case;
pub(crate) mod base_points_format_test_case;
pub(crate) mod base_postings_format_test_case;
pub(crate) mod base_segment_info_format_test_case;
pub mod base_stored_fields_format_test_case;
pub(crate) mod base_term_vectors_format_test_case;
pub mod doc_helper;
pub(crate) mod force_merge_policy;
pub mod legacy_base_doc_values_format_test_case;
mod mismatched_codec_reader;
mod mismatched_leaf_reader;
pub(crate) mod per_thread_pk_lookup;
pub mod random_index_writer;
pub(crate) mod random_postings_tester;
mod test_add_indexes;
mod test_all_file_have_codec_header;
mod test_all_files_have_checksum_footer;
mod test_approximate_priority_queue;
mod test_atomic_update;
mod test_bag_of_positions;
mod test_bag_of_postings;
pub(crate) mod test_binary_doc_values_field_updates;
mod test_binary_terms;
mod test_buffered_updates;
mod test_byte_slice_pool;
mod test_byte_slice_reader;
mod test_caching_merge_context;
mod test_codec_holds_open_files;
mod test_codecs;
mod test_concurrent_approximate_priority_queue;
mod test_consistent_field_numbers;
mod test_custom_norms;
mod test_custom_term_freq;
pub(crate) mod test_deletion_policy;
mod test_directory_reader;
mod test_directory_reader_reopen;
pub mod test_doc;
mod test_doc_count;
mod test_doc_id_merger;
pub mod test_doc_inverter_per_field_error_info;
mod test_doc_values;
mod test_doc_values_field_updates;
pub(crate) mod test_doc_values_indexing;
mod test_docs_and_positions;
mod test_docs_with_field_set;
pub(crate) mod test_document_writer;
mod test_documents_writer_delete_queue;
mod test_documents_writer_per_thread_pool;
mod test_documents_writer_stall_control;
mod test_exceed_max_term_length;
mod test_field_infos;
mod test_field_invert_state;
mod test_field_updates_buffer;
mod test_fields_reader;
mod test_filter_index_input;
pub(crate) mod test_flush_by_ram_or_counts_policy;
mod test_force_merge_forever;
mod test_frozen_buffered_updates;
mod test_index_commit;
mod test_index_file_deleter;
mod test_index_input;
mod test_index_many_documents;
mod test_index_options;
mod test_index_sorting;
mod test_index_too_many_docs;
pub(crate) mod test_index_writer;
mod test_index_writer_commit;
mod test_index_writer_delete;
mod test_index_writer_force_merge;
mod test_index_writer_from_reader;
mod test_index_writer_lock_release;
mod test_index_writer_max_docs;
pub mod test_index_writer_merge_policy;
pub(crate) mod test_index_writer_merging;
mod test_index_writer_reader;
mod test_index_writer_threads_to_segments;
mod test_index_writer_unicode;
mod test_index_writer_with_threads;
mod test_indexable_field;
mod test_indexing_sequence_numbers;
mod test_info_stream;
mod test_int_block_pool;
mod test_is_current;
mod test_lockable_concurrent_approximate_priority_queue;
mod test_log_merge_policy;
mod test_long_postings;
mod test_many_fields;
mod test_max_position;
mod test_max_term_frequency;
mod test_merge_on_flush_merge_policy;
mod test_merge_policy;
mod test_merge_rate_limiter;
mod test_mixed_codecs;
mod test_mixed_doc_values_updates;
mod test_multi_doc_values;
mod test_multi_fields;
mod test_multi_terms_enum;
mod test_never_delete;
mod test_newest_segment;
mod test_no_deletion_policy;
mod test_no_merge_policy;
mod test_no_merge_scheduler;
mod test_non_flex;
mod test_norms;
mod test_nrt_reader_cleanup;
mod test_nrt_reader_with_threads;
mod test_numeric_doc_values_field_updates;
mod test_omit_norms;
mod test_omit_positions;
pub(crate) mod test_omit_tf;
mod test_ordinal_map;
mod test_payloads;
mod test_payloads_on_vectors;
mod test_pending_deletes;
pub(crate) mod test_pending_soft_deletes;
pub(crate) mod test_per_segment_deletes;
mod test_point_values;
mod test_postings_offsets;
mod test_prefix_coded_terms;
mod test_read_only_index;
mod test_reader_closed;
mod test_reader_pool;
mod test_reader_wrapper_dv_type_check;
mod test_rollback;
mod test_rolling_updates;
mod test_same_scores_with_threads;
mod test_same_token_same_position;
mod test_segment_infos;
mod test_segment_merger;
mod test_segment_reader;
mod test_segment_term_docs;
mod test_segment_term_enum;
mod test_segment_to_thread_mapping;
mod test_size_bounded_force_merge;
mod test_sorting_codec_reader;
mod test_stress_advance;
mod test_stress_deletes;
mod test_stress_indexing;
pub mod test_stress_indexing2;
mod test_sum_doc_freq;
mod test_swapped_index_files;
mod test_term;
mod test_term_doc_perf;
mod test_term_states;
mod test_term_vectors;
mod test_term_vectors_reader;
mod test_term_vectors_writer;
mod test_terms;
mod test_terms_enum;
mod test_terms_enum2;
mod test_terms_enum_index;
pub(crate) mod test_terms_hash_per_field;
mod test_threaded_force_merge;
mod test_tiered_merge_policy;
pub(crate) mod test_transaction_rollback;
pub mod test_try_delete;
mod test_unique_term_count;
mod test_upgrade_index_merge_policy;
