/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use crate::core::index::directory_reader;
use crate::core::index::index_reader::IndexReader;
use crate::core::index::index_writer::WRITE_LOCK_NAME;
use crate::core::index::live_index_writer_config::LiveIndexWriterConfig;
use crate::core::index::merge_policy::MergePolicy;
use crate::core::index::term::Term;
use crate::core::store::IO_CONTEXT_DEFAULT;
use crate::core::store::directory::{DirEnum, Directory};
use crate::core::store::{DataInput, DataOutput, IOContext, IndexInput, IndexOutput};
use crate::core::util::close::{Closeable, CloseableRef};
use crate::core::util::error::lucene_error::{LuceneError, Result};
use crate::core::util::io_utils::IOUtils;
use crate::test_framework::core::analysis::mock_analyzer::MockAnalyzer;
use crate::test_framework::core::index::random_index_writer::RandomIndexWriter;
use crate::test_framework::core::util::line_file_docs::LineFileDocs;
use crate::test_framework::core::util::lucene_test_case::{
  is_night_mode, new_directory_shared, new_index_writer_config_with_analyzer, new_mock_directory,
  random,
};
use crate::test_framework::core::util::test_util::TestUtil;
use rand::{Rng, RngExt};
use std::sync::Arc;

/// Test that a plain default detects broken index headers early (on opening a reader).
#[allow(dead_code)] // for quick search
struct TestAllFilesCheckIndexHeader;

#[test]
fn test() -> Result<()> {
  let mut random = random();
  let dir = new_directory_shared(&mut random)?;

  let analyzer = MockAnalyzer::new(&mut random);
  let mut conf = new_index_writer_config_with_analyzer(&mut random, analyzer)?;
  conf.set_codec(TestUtil::get_default_codec());

  // Disable CFS 80% of the time so we can truncate individual files, but the other 20% of the
  // time we test truncation of .cfs/.cfe too:
  if random.random_range(0..5) != 1 {
    conf.set_use_compound_file(false);
    conf
      .get_merge_policy_mut()
      .get_base_mut()
      .set_no_cfs_ratio(0.0)?;
  }

  let riw = RandomIndexWriter::with_config(&mut random, dir.clone(), conf);
  // Use LineFileDocs so we (hopefully) get most Lucene features
  // tested, e.g. IntPoint was recently added to it:
  let mut docs = LineFileDocs::new(&mut random)?;
  for i in 0..100 {
    riw.add_document(&mut random, docs.next_doc()?)?;
    if random.random_range(0..7) == 0 {
      riw.commit(&mut random)?;
    }
    if random.random_range(0..20) == 0 {
      riw
        .delete_documents_with_terms(&mut random, vec![Term::from_text("docid", i.to_string())])?;
    }
    if random.random_range(0..15) == 0 {
      riw.w.update_numeric_doc_value(
        Term::from_text("docid", i.to_string()),
        "page_views",
        i as i64,
      )?;
    }
  }

  if !is_night_mode() {
    riw.force_merge(&mut random, 1)?;
  }
  riw.close(&mut random)?;
  check_index_header(&mut random, dir.clone())?;
  dir.close()
}

fn check_index_header<R>(random: &mut R, dir: Arc<DirEnum>) -> Result<()>
where
  R: Rng + ?Sized,
{
  for name in dir.list_all()? {
    if name != WRITE_LOCK_NAME {
      check_one_file(random, dir.clone(), &name)?;
    }
  }
  Ok(())
}

fn check_one_file<R>(random: &mut R, dir: Arc<DirEnum>, victim: &str) -> Result<()>
where
  R: Rng + ?Sized,
{
  // use ramdir explicit, as we do evil things like try to generate broken files, deletes must
  // work.
  let dir_copy = Arc::new(new_mock_directory(random)?);
  dir_copy.set_check_index_on_close(false);

  let result = (|| -> Result<()> {
    let victim_length = dir.file_length(victim)?;
    assert!(victim_length > 0);
    let wrong_bytes = TestUtil::next_usize(random, 1, 100.min(victim_length));

    if cfg!(feature = "test_log_verbose") {
      println!(
        "TEST: now break file {} by randomizing first {} of {}",
        victim, wrong_bytes, victim_length
      );
    }

    let default_context = IO_CONTEXT_DEFAULT.as_ref().map_err(Clone::clone)?;
    let read_once_context = IOContext::read_once_io_context()?;
    for name in dir.list_all()? {
      if name != victim {
        dir_copy.copy_from(dir.as_ref(), &name, &name, &default_context)?;
      } else {
        // Iterate until our randomly generated bytes are indeed different from the first bytes of
        // the file ... the vast majority of the
        // time this will only require one iteration!
        loop {
          let mut out = dir_copy.create_output(&name, &default_context)?;
          let mut input = match dir.open_input(&name, &read_once_context) {
            Ok(input) => input,
            Err(err) => {
              return IOUtils::use_or_suppress_result(Err(err), out.close());
            },
          };
          // keeps same file length, but replaces the first wrongBytes with random bytes:
          let attempt_result = (|| -> Result<bool> {
            let mut bytes = vec![0u8; wrong_bytes];
            random.fill(&mut bytes[..]);
            out.write_bytes_with_len(&bytes, bytes.len())?;
            let mut bytes2 = vec![0u8; wrong_bytes];
            input.read_bytes(&mut bytes2, 0, wrong_bytes)?;
            if bytes != bytes2 {
              // We successfully randomly generated bytes that differ from the bytes in the file:
              out.copy_bytes(&mut input, victim_length - wrong_bytes)?;
              Ok(true)
            } else {
              Ok(false)
            }
          })();
          let attempt_result = IOUtils::use_or_suppress_result(attempt_result, input.close());
          let different = IOUtils::use_or_suppress_result(attempt_result, out.close())?;
          if different {
            break;
          }
          // we have to try again, delete the first attempt and retry the loop
          dir_copy.delete_file(&name)?;
        }
      }
      dir_copy.sync(std::slice::from_ref(&name))?;
    }

    // NOTE: we .close so that if the test fails (truncation not detected) we don't also get all
    // these confusing errors about open files:
    let open_result = directory_reader::open(dir_copy.clone()).and_then(|reader| reader.close());
    match open_result {
      Err(
        LuceneError::CorruptIndex(_) | LuceneError::Eof(_) | LuceneError::IndexFormatTooOld(_),
      ) => {},
      Err(err) => return Err(err),
      Ok(()) => {
        return Err(LuceneError::illegal_state(format!(
          "broken index header in {victim} was not detected"
        )));
      },
    }

    // CheckIndex should also fail:
    let open_result = directory_reader::open(dir_copy.clone()).and_then(|reader| reader.close());
    match open_result {
      Err(
        LuceneError::CorruptIndex(_) | LuceneError::Eof(_) | LuceneError::IndexFormatTooOld(_),
      ) => Ok(()),
      Err(err) => Err(err),
      Ok(()) => Err(LuceneError::illegal_state(format!(
        "broken index header in {victim} was not detected"
      ))),
    }
  })();

  IOUtils::use_or_suppress_result(result, dir_copy.close())
}
