[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"
# format code
tidy  = "xtask tidy"
# Last command before submitting a PR
commit = "xtask commit"
# Github Actions CI
ci = "xtask ci"
# Check for uncommitted changes
check-uncommitted = "xtask check-uncommitted"
# Check License header
license-check = "xtask license-check"
