[profile.default]
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 2 }
junit = { path = "target/nextest/ci-junit.xml" }
test-threads = "num-cpus"
failure-output = "final"
success-output = "never"
status-level = "fail"
final-status-level = "fail"