extend = "../../Makefile.toml"

[tasks.tidy]
disabled=true

[tasks.commit]
disabled=true

[tasks.ci]
disabled=true

[tasks.format]
disabled=true

[tasks.clippy]
disabled=true

[tasks.fix]
disabled=true

[tasks.test]
disabled=true

[tasks.test-light]
disabled=true

[tasks.check-uncommitted]
disabled=true

[tasks.check-rust-version]
disabled=true
