name: Rust

on:
  push:
    # disable Actions with invalid branch names
    branches: [ "invalid-branch-name" ]
  pull_request:
    # disable Actions with invalid branch names
    branches: [ "invalid-branch-name" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run xtask CI
        timeout-minutes: 15
        run: cargo ci
